<?php

use Illuminate\Database\Seeder;

class CountryTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      DB::table('country')->insert(['country_code'=>'AF','country_name'=>'Afghanistan','latitude'=>'33','longitude'=>'65']);
      DB::table('country')->insert(['country_code'=>'AX','country_name'=>'Aland Islands','latitude'=>'60.25','longitude'=>'20']);
      DB::table('country')->insert(['country_code'=>'AL','country_name'=>'Albania','latitude'=>'41','longitude'=>'20']);
      DB::table('country')->insert(['country_code'=>'DZ','country_name'=>'Algeria','latitude'=>'28','longitude'=>'3']);
      DB::table('country')->insert(['country_code'=>'AS','country_name'=>'American Samoa','latitude'=>'-14.3333333333','longitude'=>'-170']);
      DB::table('country')->insert(['country_code'=>'AD','country_name'=>'Andorra','latitude'=>'42.5','longitude'=>'1.5']);
      DB::table('country')->insert(['country_code'=>'AO','country_name'=>'Angola','latitude'=>'-12.5','longitude'=>'18.5']);
      DB::table('country')->insert(['country_code'=>'AI','country_name'=>'Anguilla','latitude'=>'18.25','longitude'=>'-63.1666666667']);
      DB::table('country')->insert(['country_code'=>'AQ','country_name'=>'Antarctica','latitude'=>'-90','longitude'=>'0']);
      DB::table('country')->insert(['country_code'=>'AG','country_name'=>'Antigua and Barbuda','latitude'=>'17.05','longitude'=>'-61.8']);
      DB::table('country')->insert(['country_code'=>'AR','country_name'=>'Argentina','latitude'=>'-34','longitude'=>'-64']);
      DB::table('country')->insert(['country_code'=>'AM','country_name'=>'Armenia','latitude'=>'40','longitude'=>'45']);
      DB::table('country')->insert(['country_code'=>'AW','country_name'=>'Aruba','latitude'=>'12.5','longitude'=>'-69.9666666667']);
      DB::table('country')->insert(['country_code'=>'AU','country_name'=>'Australia','latitude'=>'-27','longitude'=>'133']);
      DB::table('country')->insert(['country_code'=>'AT','country_name'=>'Austria','latitude'=>'47.3333333333','longitude'=>'13.3333333333']);
      DB::table('country')->insert(['country_code'=>'AZ','country_name'=>'Azerbaijan','latitude'=>'40.5','longitude'=>'47.5']);
      DB::table('country')->insert(['country_code'=>'BS','country_name'=>'Bahamas','latitude'=>'24.25','longitude'=>'-76']);
      DB::table('country')->insert(['country_code'=>'BH','country_name'=>'Bahrain','latitude'=>'26','longitude'=>'50.55']);
      DB::table('country')->insert(['country_code'=>'BD','country_name'=>'Bangladesh','latitude'=>'24','longitude'=>'90']);
      DB::table('country')->insert(['country_code'=>'BB','country_name'=>'Barbados','latitude'=>'13.1666666667','longitude'=>'-59.5333333333']);
      DB::table('country')->insert(['country_code'=>'BY','country_name'=>'Belarus','latitude'=>'53','longitude'=>'28']);
      DB::table('country')->insert(['country_code'=>'BE','country_name'=>'Belgium','latitude'=>'50.8333333333','longitude'=>'4']);
      DB::table('country')->insert(['country_code'=>'BZ','country_name'=>'Belize','latitude'=>'17.25','longitude'=>'-88.75']);
      DB::table('country')->insert(['country_code'=>'BJ','country_name'=>'Benin','latitude'=>'9.5','longitude'=>'2.25']);
      DB::table('country')->insert(['country_code'=>'BM','country_name'=>'Bermuda','latitude'=>'32.3333333333','longitude'=>'-64.75']);
      DB::table('country')->insert(['country_code'=>'BT','country_name'=>'Bhutan','latitude'=>'27.5','longitude'=>'90.5']);
      DB::table('country')->insert(['country_code'=>'BO','country_name'=>'Bolivia, Plurinational State of','latitude'=>'-17','longitude'=>'-65']);
      DB::table('country')->insert(['country_code'=>'BQ','country_name'=>'Bonaire, Sint Eustatius and Saba','latitude'=>'12.1666666667','longitude'=>'-68.25']);
      DB::table('country')->insert(['country_code'=>'BA','country_name'=>'Bosnia and Herzegovina','latitude'=>'44','longitude'=>'18']);
      DB::table('country')->insert(['country_code'=>'BW','country_name'=>'Botswana','latitude'=>'-22','longitude'=>'24']);
      DB::table('country')->insert(['country_code'=>'BV','country_name'=>'Bouvet Island','latitude'=>'-54.4333333333','longitude'=>'3.4']);
      DB::table('country')->insert(['country_code'=>'BR','country_name'=>'Brazil','latitude'=>'-10','longitude'=>'-55']);
      DB::table('country')->insert(['country_code'=>'IO','country_name'=>'British Indian Ocean Territory','latitude'=>'-6','longitude'=>'71.5']);
      DB::table('country')->insert(['country_code'=>'BN','country_name'=>'Brunei Darussalam','latitude'=>'4.5','longitude'=>'114.666666667']);
      DB::table('country')->insert(['country_code'=>'BG','country_name'=>'Bulgaria','latitude'=>'43','longitude'=>'25']);
      DB::table('country')->insert(['country_code'=>'BF','country_name'=>'Burkina Faso','latitude'=>'13','longitude'=>'-2']);
      DB::table('country')->insert(['country_code'=>'BI','country_name'=>'Burundi','latitude'=>'-3.5','longitude'=>'30']);
      DB::table('country')->insert(['country_code'=>'KH','country_name'=>'Cambodia','latitude'=>'13','longitude'=>'105']);
      DB::table('country')->insert(['country_code'=>'CM','country_name'=>'Cameroon','latitude'=>'6','longitude'=>'12']);
      DB::table('country')->insert(['country_code'=>'CA','country_name'=>'Canada','latitude'=>'60','longitude'=>'-95']);
      DB::table('country')->insert(['country_code'=>'CV','country_name'=>'Cape Verde','latitude'=>'16','longitude'=>'-24']);
      DB::table('country')->insert(['country_code'=>'KY','country_name'=>'Cayman Islands','latitude'=>'19.5','longitude'=>'-80.5']);
      DB::table('country')->insert(['country_code'=>'CF','country_name'=>'Central African Republic','latitude'=>'7','longitude'=>'21']);
      DB::table('country')->insert(['country_code'=>'TD','country_name'=>'Chad','latitude'=>'15','longitude'=>'19']);
      DB::table('country')->insert(['country_code'=>'CL','country_name'=>'Chile','latitude'=>'-30','longitude'=>'-71']);
      DB::table('country')->insert(['country_code'=>'CN','country_name'=>'China','latitude'=>'35','longitude'=>'105']);
      DB::table('country')->insert(['country_code'=>'CX','country_name'=>'Christmas Island','latitude'=>'-10.5','longitude'=>'105.666666667']);
      DB::table('country')->insert(['country_code'=>'CC','country_name'=>'Cocos (Keeling) Islands','latitude'=>'-12.5','longitude'=>'96.8333333333']);
      DB::table('country')->insert(['country_code'=>'CO','country_name'=>'Colombia','latitude'=>'4','longitude'=>'-72']);
      DB::table('country')->insert(['country_code'=>'KM','country_name'=>'Comoros','latitude'=>'-12.1666666667','longitude'=>'44.25']);
      DB::table('country')->insert(['country_code'=>'CG','country_name'=>'Congo','latitude'=>'-1','longitude'=>'15']);
      DB::table('country')->insert(['country_code'=>'CD','country_name'=>'Congo, The Democratic Republic of the','latitude'=>'0.0166666666667','longitude'=>'25']);
      DB::table('country')->insert(['country_code'=>'CK','country_name'=>'Cook Islands','latitude'=>'-21.2333333333','longitude'=>'-159.766666667']);
      DB::table('country')->insert(['country_code'=>'CR','country_name'=>'Costa Rica','latitude'=>'10','longitude'=>'-84']);
      DB::table('country')->insert(['country_code'=>'CI','country_name'=>'Cote d Ivoire','latitude'=>'8','longitude'=>'-5']);
      DB::table('country')->insert(['country_code'=>'HR','country_name'=>'Croatia','latitude'=>'45.1666666667','longitude'=>'15.5']);
      DB::table('country')->insert(['country_code'=>'CU','country_name'=>'Cuba','latitude'=>'21.5','longitude'=>'-80']);
      DB::table('country')->insert(['country_code'=>'CW','country_name'=>'Curacao','latitude'=>'12.1666666667','longitude'=>'-69']);
      DB::table('country')->insert(['country_code'=>'CY','country_name'=>'Cyprus','latitude'=>'35','longitude'=>'33']);
      DB::table('country')->insert(['country_code'=>'CZ','country_name'=>'Czech Republic','latitude'=>'49.75','longitude'=>'15.5']);
      DB::table('country')->insert(['country_code'=>'DK','country_name'=>'Denmark','latitude'=>'56','longitude'=>'10']);
      DB::table('country')->insert(['country_code'=>'DJ','country_name'=>'Djibouti','latitude'=>'11.5','longitude'=>'43']);
      DB::table('country')->insert(['country_code'=>'DM','country_name'=>'Dominica','latitude'=>'15.4166666667','longitude'=>'-61.3333333333']);
      DB::table('country')->insert(['country_code'=>'DO','country_name'=>'Dominican Republic','latitude'=>'19','longitude'=>'-70.6666666667']);
      DB::table('country')->insert(['country_code'=>'EC','country_name'=>'Ecuador','latitude'=>'-2','longitude'=>'-77.5']);
      DB::table('country')->insert(['country_code'=>'EG','country_name'=>'Egypt','latitude'=>'27','longitude'=>'30']);
      DB::table('country')->insert(['country_code'=>'SV','country_name'=>'El Salvador','latitude'=>'13.8333333333','longitude'=>'-88.9166666667']);
      DB::table('country')->insert(['country_code'=>'GQ','country_name'=>'Equatorial Guinea','latitude'=>'2','longitude'=>'10']);
      DB::table('country')->insert(['country_code'=>'ER','country_name'=>'Eritrea','latitude'=>'15','longitude'=>'39']);
      DB::table('country')->insert(['country_code'=>'EE','country_name'=>'Estonia','latitude'=>'59','longitude'=>'26']);
      DB::table('country')->insert(['country_code'=>'ET','country_name'=>'Ethiopia','latitude'=>'8','longitude'=>'38']);
      DB::table('country')->insert(['country_code'=>'FK','country_name'=>'Falkland Islands (Malvinas)','latitude'=>'-51.75','longitude'=>'-59']);
      DB::table('country')->insert(['country_code'=>'FO','country_name'=>'Faroe Islands','latitude'=>'62','longitude'=>'-7']);
      DB::table('country')->insert(['country_code'=>'FJ','country_name'=>'Fiji','latitude'=>'-18','longitude'=>'175']);
      DB::table('country')->insert(['country_code'=>'FI','country_name'=>'Finland','latitude'=>'64','longitude'=>'26']);
      DB::table('country')->insert(['country_code'=>'FR','country_name'=>'France','latitude'=>'46','longitude'=>'2']);
      DB::table('country')->insert(['country_code'=>'GF','country_name'=>'French Guiana','latitude'=>'4','longitude'=>'-53']);
      DB::table('country')->insert(['country_code'=>'PF','country_name'=>'French Polynesia','latitude'=>'-15','longitude'=>'-140']);
      DB::table('country')->insert(['country_code'=>'TF','country_name'=>'French Southern Territories','latitude'=>'-37.8333333333','longitude'=>'77.5333333333']);
      DB::table('country')->insert(['country_code'=>'GA','country_name'=>'Gabon','latitude'=>'-1','longitude'=>'11.75']);
      DB::table('country')->insert(['country_code'=>'GM','country_name'=>'Gambia','latitude'=>'13.4666666667','longitude'=>'-16.5666666667']);
      DB::table('country')->insert(['country_code'=>'GE','country_name'=>'Georgia','latitude'=>'42','longitude'=>'43.5']);
      DB::table('country')->insert(['country_code'=>'DE','country_name'=>'Germany','latitude'=>'51','longitude'=>'9']);
      DB::table('country')->insert(['country_code'=>'GH','country_name'=>'Ghana','latitude'=>'8','longitude'=>'-2']);
      DB::table('country')->insert(['country_code'=>'GI','country_name'=>'Gibraltar','latitude'=>'36.1333333333','longitude'=>'-5.35']);
      DB::table('country')->insert(['country_code'=>'GR','country_name'=>'Greece','latitude'=>'39','longitude'=>'22']);
      DB::table('country')->insert(['country_code'=>'GL','country_name'=>'Greenland','latitude'=>'72','longitude'=>'-40']);
      DB::table('country')->insert(['country_code'=>'GD','country_name'=>'Grenada','latitude'=>'12.1166666667','longitude'=>'-61.6666666667']);
      DB::table('country')->insert(['country_code'=>'GP','country_name'=>'Guadeloupe','latitude'=>'16.25','longitude'=>'-61.5833333333']);
      DB::table('country')->insert(['country_code'=>'GU','country_name'=>'Guam','latitude'=>'13.4666666667','longitude'=>'144.783333333']);
      DB::table('country')->insert(['country_code'=>'GT','country_name'=>'Guatemala','latitude'=>'15.5','longitude'=>'-90.25']);
      DB::table('country')->insert(['country_code'=>'GG','country_name'=>'Guernsey','latitude'=>'49.4666666667','longitude'=>'-2.58333333333']);
      DB::table('country')->insert(['country_code'=>'GN','country_name'=>'Guinea','latitude'=>'11','longitude'=>'-10']);
      DB::table('country')->insert(['country_code'=>'GW','country_name'=>'Guinea-Bissau','latitude'=>'12','longitude'=>'-15']);
      DB::table('country')->insert(['country_code'=>'GY','country_name'=>'Guyana','latitude'=>'5','longitude'=>'-59']);
      DB::table('country')->insert(['country_code'=>'HT','country_name'=>'Haiti','latitude'=>'19','longitude'=>'-72.4166666667']);
      DB::table('country')->insert(['country_code'=>'HM','country_name'=>'Heard Island and McDonald Islands','latitude'=>'-53.1','longitude'=>'72.5166666667']);
      DB::table('country')->insert(['country_code'=>'VA','country_name'=>'Holy See (Vatican City State)','latitude'=>'41.9','longitude'=>'12.45']);
      DB::table('country')->insert(['country_code'=>'HN','country_name'=>'Honduras','latitude'=>'15','longitude'=>'-86.5']);
      DB::table('country')->insert(['country_code'=>'HK','country_name'=>'Hong Kong','latitude'=>'22.25','longitude'=>'114.166666667']);
      DB::table('country')->insert(['country_code'=>'HU','country_name'=>'Hungary','latitude'=>'47','longitude'=>'20']);
      DB::table('country')->insert(['country_code'=>'IS','country_name'=>'Iceland','latitude'=>'65','longitude'=>'-18']);
      DB::table('country')->insert(['country_code'=>'IN','country_name'=>'India','latitude'=>'20','longitude'=>'77']);
      DB::table('country')->insert(['country_code'=>'ID','country_name'=>'Indonesia','latitude'=>'-5','longitude'=>'120']);
      DB::table('country')->insert(['country_code'=>'IR','country_name'=>'Iran, Islamic Republic of','latitude'=>'32','longitude'=>'53']);
      DB::table('country')->insert(['country_code'=>'IQ','country_name'=>'Iraq','latitude'=>'33','longitude'=>'44']);
      DB::table('country')->insert(['country_code'=>'IE','country_name'=>'Ireland','latitude'=>'53','longitude'=>'-8']);
      DB::table('country')->insert(['country_code'=>'IM','country_name'=>'Isle of Man','latitude'=>'54.25','longitude'=>'-4.5']);
      DB::table('country')->insert(['country_code'=>'IL','country_name'=>'Israel','latitude'=>'31.5','longitude'=>'34.75']);
      DB::table('country')->insert(['country_code'=>'IT','country_name'=>'Italy','latitude'=>'42.8333333333','longitude'=>'12.8333333333']);
      DB::table('country')->insert(['country_code'=>'JM','country_name'=>'Jamaica','latitude'=>'18.25','longitude'=>'-77.5']);
      DB::table('country')->insert(['country_code'=>'JP','country_name'=>'Japan','latitude'=>'36','longitude'=>'138']);
      DB::table('country')->insert(['country_code'=>'JE','country_name'=>'Jersey','latitude'=>'49.25','longitude'=>'-2.16666666667']);
      DB::table('country')->insert(['country_code'=>'JO','country_name'=>'Jordan','latitude'=>'31','longitude'=>'36']);
      DB::table('country')->insert(['country_code'=>'KZ','country_name'=>'Kazakhstan','latitude'=>'48','longitude'=>'68']);
      DB::table('country')->insert(['country_code'=>'KE','country_name'=>'Kenya','latitude'=>'1','longitude'=>'38']);
      DB::table('country')->insert(['country_code'=>'KI','country_name'=>'Kiribati','latitude'=>'1.41666666667','longitude'=>'173']);
      DB::table('country')->insert(['country_code'=>'KP','country_name'=>'Korea, Democratic People\s Republic of','latitude'=>'40','longitude'=>'127']);
      DB::table('country')->insert(['country_code'=>'KR','country_name'=>'Korea, Republic of','latitude'=>'37','longitude'=>'127.5']);
      DB::table('country')->insert(['country_code'=>'KW','country_name'=>'Kuwait','latitude'=>'29.366667','longitude'=>'47.966667']);
      DB::table('country')->insert(['country_code'=>'KG','country_name'=>'Kyrgyzstan','latitude'=>'41','longitude'=>'75']);
      DB::table('country')->insert(['country_code'=>'LA','country_name'=>'Lao People\s Democratic Republic','latitude'=>'18','longitude'=>'105']);
      DB::table('country')->insert(['country_code'=>'LV','country_name'=>'Latvia','latitude'=>'57','longitude'=>'25']);
      DB::table('country')->insert(['country_code'=>'LB','country_name'=>'Lebanon','latitude'=>'33.8333333333','longitude'=>'35.8333333333']);
      DB::table('country')->insert(['country_code'=>'LS','country_name'=>'Lesotho','latitude'=>'-29.5','longitude'=>'28.5']);
      DB::table('country')->insert(['country_code'=>'LR','country_name'=>'Liberia','latitude'=>'6.5','longitude'=>'-9.5']);
      DB::table('country')->insert(['country_code'=>'LY','country_name'=>'Libyan Arab Jamahiriya','latitude'=>'25','longitude'=>'17']);
      DB::table('country')->insert(['country_code'=>'LI','country_name'=>'Liechtenstein','latitude'=>'47.2666666667','longitude'=>'9.53333333333']);
      DB::table('country')->insert(['country_code'=>'LT','country_name'=>'Lithuania','latitude'=>'56','longitude'=>'24']);
      DB::table('country')->insert(['country_code'=>'LU','country_name'=>'Luxembourg','latitude'=>'49.75','longitude'=>'6.16666666667']);
      DB::table('country')->insert(['country_code'=>'MO','country_name'=>'Macao','latitude'=>'22.1666666667','longitude'=>'113.55']);
      DB::table('country')->insert(['country_code'=>'MK','country_name'=>'Macedonia, The Former Yugoslav Republic of','latitude'=>'41.8333333333','longitude'=>'22']);
      DB::table('country')->insert(['country_code'=>'MG','country_name'=>'Madagascar','latitude'=>'-20','longitude'=>'47']);
      DB::table('country')->insert(['country_code'=>'MW','country_name'=>'Malawi','latitude'=>'-13.5','longitude'=>'34']);
      DB::table('country')->insert(['country_code'=>'MY','country_name'=>'Malaysia','latitude'=>'2.5','longitude'=>'112.5']);
      DB::table('country')->insert(['country_code'=>'MV','country_name'=>'Maldives','latitude'=>'3.25','longitude'=>'73']);
      DB::table('country')->insert(['country_code'=>'ML','country_name'=>'Mali','latitude'=>'17','longitude'=>'-4']);
      DB::table('country')->insert(['country_code'=>'MT','country_name'=>'Malta','latitude'=>'35.8333333333','longitude'=>'14.5833333333']);
      DB::table('country')->insert(['country_code'=>'MH','country_name'=>'Marshall Islands','latitude'=>'9','longitude'=>'168']);
      DB::table('country')->insert(['country_code'=>'MQ','country_name'=>'Martinique','latitude'=>'14.6','longitude'=>'-61.0833333333']);
      DB::table('country')->insert(['country_code'=>'MR','country_name'=>'Mauritania','latitude'=>'20','longitude'=>'-12']);
      DB::table('country')->insert(['country_code'=>'MU','country_name'=>'Mauritius','latitude'=>'-20.2833333333','longitude'=>'57.55']);
      DB::table('country')->insert(['country_code'=>'YT','country_name'=>'Mayotte','latitude'=>'-12.8333333333','longitude'=>'45.1666666667']);
      DB::table('country')->insert(['country_code'=>'MX','country_name'=>'Mexico','latitude'=>'23','longitude'=>'-102']);
      DB::table('country')->insert(['country_code'=>'FM','country_name'=>'Micronesia, Federated States of','latitude'=>'6.91666666667','longitude'=>'158.25']);
      DB::table('country')->insert(['country_code'=>'MD','country_name'=>'Moldova, Republic of','latitude'=>'47','longitude'=>'29']);
      DB::table('country')->insert(['country_code'=>'MC','country_name'=>'Monaco','latitude'=>'43.732778','longitude'=>'7.419722']);
      DB::table('country')->insert(['country_code'=>'MN','country_name'=>'Mongolia','latitude'=>'46','longitude'=>'105']);
      DB::table('country')->insert(['country_code'=>'ME','country_name'=>'Montenegro','latitude'=>'42.5','longitude'=>'19.3']);
      DB::table('country')->insert(['country_code'=>'MS','country_name'=>'Montserrat','latitude'=>'16.75','longitude'=>'-62.2']);
      DB::table('country')->insert(['country_code'=>'MA','country_name'=>'Morocco','latitude'=>'32','longitude'=>'-5']);
      DB::table('country')->insert(['country_code'=>'MZ','country_name'=>'Mozambique','latitude'=>'-18.25','longitude'=>'35']);
      DB::table('country')->insert(['country_code'=>'MM','country_name'=>'Myanmar','latitude'=>'22','longitude'=>'98']);
      DB::table('country')->insert(['country_code'=>'NA','country_name'=>'Namibia','latitude'=>'-22','longitude'=>'17']);
      DB::table('country')->insert(['country_code'=>'NR','country_name'=>'Nauru','latitude'=>'-0.533333333333','longitude'=>'166.916666667']);
      DB::table('country')->insert(['country_code'=>'NP','country_name'=>'Nepal','latitude'=>'28','longitude'=>'84']);
      DB::table('country')->insert(['country_code'=>'NL','country_name'=>'Netherlands','latitude'=>'52.5','longitude'=>'5.75']);
      DB::table('country')->insert(['country_code'=>'NC','country_name'=>'New Caledonia','latitude'=>'-21.5','longitude'=>'165.5']);
      DB::table('country')->insert(['country_code'=>'NZ','country_name'=>'New Zealand','latitude'=>'-41','longitude'=>'174']);
      DB::table('country')->insert(['country_code'=>'NI','country_name'=>'Nicaragua','latitude'=>'13','longitude'=>'-85']);
      DB::table('country')->insert(['country_code'=>'NE','country_name'=>'Niger','latitude'=>'16','longitude'=>'8']);
      DB::table('country')->insert(['country_code'=>'NG','country_name'=>'Nigeria','latitude'=>'10','longitude'=>'8']);
      DB::table('country')->insert(['country_code'=>'NU','country_name'=>'Niue','latitude'=>'-19.0333333333','longitude'=>'-169.866666667']);
      DB::table('country')->insert(['country_code'=>'NF','country_name'=>'Norfolk Island','latitude'=>'-29.0333333333','longitude'=>'167.95']);
      DB::table('country')->insert(['country_code'=>'MP','country_name'=>'Northern Mariana Islands','latitude'=>'15.2','longitude'=>'145.75']);
      DB::table('country')->insert(['country_code'=>'NO','country_name'=>'Norway','latitude'=>'62','longitude'=>'10']);
      DB::table('country')->insert(['country_code'=>'PS','country_name'=>'Occupied Palestinian Territory','latitude'=>'32','longitude'=>'35.25']);
      DB::table('country')->insert(['country_code'=>'OM','country_name'=>'Oman','latitude'=>'21','longitude'=>'57']);
      DB::table('country')->insert(['country_code'=>'PK','country_name'=>'Pakistan','latitude'=>'30','longitude'=>'70']);
      DB::table('country')->insert(['country_code'=>'PW','country_name'=>'Palau','latitude'=>'7.5','longitude'=>'134.5']);
      DB::table('country')->insert(['country_code'=>'PA','country_name'=>'Panama','latitude'=>'9','longitude'=>'-80']);
      DB::table('country')->insert(['country_code'=>'PG','country_name'=>'Papua New Guinea','latitude'=>'-6','longitude'=>'147']);
      DB::table('country')->insert(['country_code'=>'PY','country_name'=>'Paraguay','latitude'=>'-23','longitude'=>'-58']);
      DB::table('country')->insert(['country_code'=>'PE','country_name'=>'Peru','latitude'=>'-10','longitude'=>'-76']);
      DB::table('country')->insert(['country_code'=>'PH','country_name'=>'Philippines','latitude'=>'13','longitude'=>'122']);
      DB::table('country')->insert(['country_code'=>'PN','country_name'=>'Pitcairn','latitude'=>'-25.0666666667','longitude'=>'-130.1']);
      DB::table('country')->insert(['country_code'=>'PL','country_name'=>'Poland','latitude'=>'52','longitude'=>'20']);
      DB::table('country')->insert(['country_code'=>'PT','country_name'=>'Portugal','latitude'=>'39.5','longitude'=>'-8']);
      DB::table('country')->insert(['country_code'=>'PR','country_name'=>'Puerto Rico','latitude'=>'18.25','longitude'=>'-66.5']);
      DB::table('country')->insert(['country_code'=>'QA','country_name'=>'Qatar','latitude'=>'25.5','longitude'=>'51.25']);
      DB::table('country')->insert(['country_code'=>'RE','country_name'=>'Reunion','latitude'=>'-21.1','longitude'=>'55.6']);
      DB::table('country')->insert(['country_code'=>'RO','country_name'=>'Romania','latitude'=>'46','longitude'=>'25']);
      DB::table('country')->insert(['country_code'=>'RU','country_name'=>'Russian Federation','latitude'=>'60','longitude'=>'100']);
      DB::table('country')->insert(['country_code'=>'RW','country_name'=>'Rwanda','latitude'=>'-2','longitude'=>'30']);
      DB::table('country')->insert(['country_code'=>'BL','country_name'=>'Saint Barthelemy','latitude'=>'17.9','longitude'=>'-62.833333']);
      DB::table('country')->insert(['country_code'=>'SH','country_name'=>'Saint Helena, Ascension and Tristan da Cunha','latitude'=>'-15.95','longitude'=>'-5.7']);
      DB::table('country')->insert(['country_code'=>'KN','country_name'=>'Saint Kitts and Nevis','latitude'=>'17.3333333333','longitude'=>'-62.75']);
      DB::table('country')->insert(['country_code'=>'LC','country_name'=>'Saint Lucia','latitude'=>'13.8833333333','longitude'=>'-60.9666666667']);
      DB::table('country')->insert(['country_code'=>'MF','country_name'=>'Saint Martin (French part)','latitude'=>'18.075278','longitude'=>'-63.06']);
      DB::table('country')->insert(['country_code'=>'PM','country_name'=>'Saint Pierre and Miquelon','latitude'=>'46.8333333333','longitude'=>'-56.3333333333']);
      DB::table('country')->insert(['country_code'=>'VC','country_name'=>'Saint Vincent and The Grenadines','latitude'=>'13.25','longitude'=>'-61.2']);
      DB::table('country')->insert(['country_code'=>'WS','country_name'=>'Samoa','latitude'=>'-13.5833333333','longitude'=>'-172.333333333']);
      DB::table('country')->insert(['country_code'=>'SM','country_name'=>'San Marino','latitude'=>'43.933333','longitude'=>'12.4166666667']);
      DB::table('country')->insert(['country_code'=>'ST','country_name'=>'Sao Tome and Principe','latitude'=>'1','longitude'=>'7']);
      DB::table('country')->insert(['country_code'=>'SA','country_name'=>'Saudi Arabia','latitude'=>'25','longitude'=>'45']);
      DB::table('country')->insert(['country_code'=>'SN','country_name'=>'Senegal','latitude'=>'14','longitude'=>'-14']);
      DB::table('country')->insert(['country_code'=>'RS','country_name'=>'Serbia','latitude'=>'44','longitude'=>'21']);
      DB::table('country')->insert(['country_code'=>'SC','country_name'=>'Seychelles','latitude'=>'-4.58333333333','longitude'=>'55.6666666667']);
      DB::table('country')->insert(['country_code'=>'SL','country_name'=>'Sierra Leone','latitude'=>'8.5','longitude'=>'-11.5']);
      DB::table('country')->insert(['country_code'=>'SG','country_name'=>'Singapore','latitude'=>'1.36666666667','longitude'=>'103.8']);
      DB::table('country')->insert(['country_code'=>'SX','country_name'=>'Sint Maarten (Dutch part)','latitude'=>'18.04167','longitude'=>'-63.06667']);
      DB::table('country')->insert(['country_code'=>'SK','country_name'=>'Slovakia','latitude'=>'48.6666666667','longitude'=>'19.5']);
      DB::table('country')->insert(['country_code'=>'SI','country_name'=>'Slovenia','latitude'=>'46.1166666667','longitude'=>'14.8166666667']);
      DB::table('country')->insert(['country_code'=>'SB','country_name'=>'Solomon Islands','latitude'=>'-8','longitude'=>'159']);
      DB::table('country')->insert(['country_code'=>'SO','country_name'=>'Somalia','latitude'=>'10','longitude'=>'49']);
      DB::table('country')->insert(['country_code'=>'ZA','country_name'=>'South Africa','latitude'=>'-29','longitude'=>'24']);
      DB::table('country')->insert(['country_code'=>'GS','country_name'=>'South Georgia and the South Sandwich Islands','latitude'=>'-54.5','longitude'=>'-37']);
      DB::table('country')->insert(['country_code'=>'SS','country_name'=>'South Sudan','latitude'=>'8','longitude'=>'30']);
      DB::table('country')->insert(['country_code'=>'ES','country_name'=>'Spain','latitude'=>'40','longitude'=>'-4']);
      DB::table('country')->insert(['country_code'=>'LK','country_name'=>'Sri Lanka','latitude'=>'7','longitude'=>'81']);
      DB::table('country')->insert(['country_code'=>'SD','country_name'=>'Sudan','latitude'=>'15','longitude'=>'30']);
      DB::table('country')->insert(['country_code'=>'SR','country_name'=>'Suriname','latitude'=>'4','longitude'=>'-56']);
      DB::table('country')->insert(['country_code'=>'SJ','country_name'=>'Svalbard and Jan Mayen','latitude'=>'78','longitude'=>'20']);
      DB::table('country')->insert(['country_code'=>'SZ','country_name'=>'Swaziland','latitude'=>'-26.5','longitude'=>'31.5']);
      DB::table('country')->insert(['country_code'=>'SE','country_name'=>'Sweden','latitude'=>'62','longitude'=>'15']);
      DB::table('country')->insert(['country_code'=>'CH','country_name'=>'Switzerland','latitude'=>'47','longitude'=>'8']);
      DB::table('country')->insert(['country_code'=>'SY','country_name'=>'Syrian Arab Republic','latitude'=>'35','longitude'=>'38']);
      DB::table('country')->insert(['country_code'=>'TW','country_name'=>'Taiwan, Province of China','latitude'=>'23.5','longitude'=>'121']);
      DB::table('country')->insert(['country_code'=>'TJ','country_name'=>'Tajikistan','latitude'=>'39','longitude'=>'71']);
      DB::table('country')->insert(['country_code'=>'TZ','country_name'=>'Tanzania, United Republic of','latitude'=>'-6','longitude'=>'35']);
      DB::table('country')->insert(['country_code'=>'TH','country_name'=>'Thailand','latitude'=>'15','longitude'=>'100']);
      DB::table('country')->insert(['country_code'=>'TL','country_name'=>'Timor-Leste','latitude'=>'-8.83333333333','longitude'=>'125.916666667']);
      DB::table('country')->insert(['country_code'=>'TG','country_name'=>'Togo','latitude'=>'8','longitude'=>'1.16666666667']);
      DB::table('country')->insert(['country_code'=>'TK','country_name'=>'Tokelau','latitude'=>'-9','longitude'=>'-172']);
      DB::table('country')->insert(['country_code'=>'TO','country_name'=>'Tonga','latitude'=>'-20','longitude'=>'-175']);
      DB::table('country')->insert(['country_code'=>'TT','country_name'=>'Trinidad and Tobago','latitude'=>'11','longitude'=>'-61']);
      DB::table('country')->insert(['country_code'=>'TN','country_name'=>'Tunisia','latitude'=>'34','longitude'=>'9']);
      DB::table('country')->insert(['country_code'=>'TR','country_name'=>'Turkey','latitude'=>'39','longitude'=>'35']);
      DB::table('country')->insert(['country_code'=>'TM','country_name'=>'Turkmenistan','latitude'=>'40','longitude'=>'60']);
      DB::table('country')->insert(['country_code'=>'TC','country_name'=>'Turks and Caicos Islands','latitude'=>'21.75','longitude'=>'-71.5833333333']);
      DB::table('country')->insert(['country_code'=>'TV','country_name'=>'Tuvalu','latitude'=>'-8','longitude'=>'178']);
      DB::table('country')->insert(['country_code'=>'UG','country_name'=>'Uganda','latitude'=>'1','longitude'=>'32']);
      DB::table('country')->insert(['country_code'=>'UA','country_name'=>'Ukraine','latitude'=>'49','longitude'=>'32']);
      DB::table('country')->insert(['country_code'=>'AE','country_name'=>'United Arab Emirates','latitude'=>'24','longitude'=>'54']);
      DB::table('country')->insert(['country_code'=>'GB','country_name'=>'United Kingdom','latitude'=>'54','longitude'=>'-2']);
      DB::table('country')->insert(['country_code'=>'US','country_name'=>'United States','latitude'=>'38','longitude'=>'-97']);
      DB::table('country')->insert(['country_code'=>'UM','country_name'=>'United States Minor Outlying Islands','latitude'=>'16.75','longitude'=>'-169.516666667']);
      DB::table('country')->insert(['country_code'=>'UY','country_name'=>'Uruguay','latitude'=>'-33','longitude'=>'-56']);
      DB::table('country')->insert(['country_code'=>'UZ','country_name'=>'Uzbekistan','latitude'=>'41','longitude'=>'64']);
      DB::table('country')->insert(['country_code'=>'VU','country_name'=>'Vanuatu','latitude'=>'-16','longitude'=>'167']);
      DB::table('country')->insert(['country_code'=>'VE','country_name'=>'Venezuela, Bolivarian Republic of','latitude'=>'8','longitude'=>'-66']);
      DB::table('country')->insert(['country_code'=>'VN','country_name'=>'Viet Nam','latitude'=>'16.1666666667','longitude'=>'107.833333333']);
      DB::table('country')->insert(['country_code'=>'VG','country_name'=>'Virgin Islands, British','latitude'=>'18.5','longitude'=>'-64.5']);
      DB::table('country')->insert(['country_code'=>'VI','country_name'=>'Virgin Islands, U.S.','latitude'=>'18.3333333333','longitude'=>'-64.8333333333']);
      DB::table('country')->insert(['country_code'=>'WF','country_name'=>'Wallis and Futuna','latitude'=>'-13.3','longitude'=>'-176.2']);
      DB::table('country')->insert(['country_code'=>'EH','country_name'=>'Western Sahara','latitude'=>'24.5','longitude'=>'-13']);
      DB::table('country')->insert(['country_code'=>'YE','country_name'=>'Yemen','latitude'=>'15','longitude'=>'48']);
      DB::table('country')->insert(['country_code'=>'ZM','country_name'=>'Zambia','latitude'=>'-15','longitude'=>'30']);
      DB::table('country')->insert(['country_code'=>'ZW','country_name'=>'Zimbabwe','latitude'=>'-20','longitude'=>'30']);
    }
}
